# file: cassandra/tasks/user.yml

- name: Cassandra | Make sure the cassandra group is present
  group:
    gid: "{{cassandra_gid}}"
    name: "{{cassandra_group}}"
    state: present

- name: Cassandra | Make sure the cassandra user directory
  file:
    path: "{{cassandra_user_dir}}"
    state: directory

- name: Cassandra | Make sure the cassandra user is present
  user:
    name: "{{cassandra_user}}"
    uid: "{{cassandra_uid}}"
    group: "{{cassandra_group}}"
    comment: "Cassandra user"
    home: "{{cassandra_user_dir}}"
    shell: /bin/bash
    state: present

- name: Cassandra | Set the right directory permissions for the www directory
  file:
    path: "{{cassandra_user_dir}}"
    owner: "{{cassandra_user}}"
    group: "{{cassandra_group}}"
    mode: 0700
    state: directory

- name: Cassandra | Set the right expiration on the cassandra user
  command: "sudo chage -I -1 -E -1 -m -1 -M -1 -W -1 -E -1 {{cassandra_user}}"
