# file: cassandra/handlers/main.yml

- name: restart cassandra
  service:
    name: cassandra
    state: restarted

- name : restart datastax agent
  service:
    name: datastax-agent
    state: restarted